*Main.c file generated by New Project wizard
 *
 * Created:   sat. oct. 30 2021
 * Processor: PIC16F84A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#pragma config FOSC = HS
#pragma config WDTE = OFF

//delay
#define FRECUENCIA 1000000L
#define delay_us(x){	unsigned int us; \
	us = (x)/(12000000/FRECUENCIA)|1; \
	while(--us != 0) continue;}
	
void delay_ms(unsigned int ms){teamste
	unsigned int i;
	do{
		i=4;
		do{
		   delay_us(64);
		}while(--i);
	}while(--ms);
}
	
#define _XTAL_FREQ 4000000
unsigned char tabla[10] = {0x3f, 0x06,0x5b, 0x4f, 0x66, 0x6d, 0x7d, 0x07, 0x7f, 0x6f};


//void blink(void);
void display(unsigned char ud, unsigned char dec);

void main(void){
   
   unsigned char ud=0,dec=0;
   
	 OPTION_REG=0x38; //configuracion del timer0
	 TRISA = 0b011111000; //se configuran entradas
	TRISB = 0; // para el portb todos son salida
	PORTB = 0x00; //apagar todos los pines del portb
	TMR0 =0; //inicializar el timer en 0
   //blink();

   
	while(1){
	   //lo que hace que se repita
if(RA3 == 1){
   //reset
   TMR0 = 0;
   dec= 0;
   ud = 0;
   //blink();
}


display(tabla[ud], tabla[dec]);
while(RA4 == 1){
   //TMR0++;
   ud = TMR0;
   if(ud == 10){
      ud=0;
      dec++;
      TMR0 = 0;
      }
    if(dec == 10){
       dec=0;
       }
       
       //mostrar en pantalla
       display(tabla[ud], tabla[dec]);
   }
	}
     }

//encender el display
void display(unsigned char unidad, unsigned char decena){
      PORTA=0x01;
   PORTB = unidad;
   delay_ms(30);
   
   
   
   PORTA = 0x02;
   PORTB = decena;
   delay_ms(30);
   
   }
   
   void blink(void){
      unsigned char id;
      for(id = 0; id<10; id++){
	 display(0x40, 0x40);
	 }
      }
